FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# modemo

API for getting bias analysis of Facebook account and/or an article.

## Facebook Login [/login]

### Login [GET]

User should be able to log in with their Facebook account; need to decide what information is needed for frontend to process and send to backend.

+ Response 200 (application/json)

        [
            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 2048
                    }, {
                        "choice": "Python",
                        "votes": 1024
                    }, {
                        "choice": "Objective-C",
                        "votes": 512
                    }, {
                        "choice": "Ruby",
                        "votes": 256
                    }
                ]
            }
        ]

## Non-Facebook Analysis [/analyze]
### Analyze Article [POST]

Given an article link, send to backend server for processing. Server response should be 200 with a ton of information (stats, article sentences mapped to their bias indices)

+ Request (application/json)

        {
            "url": https://google.com
        }

+ Response 200 (application/json)

    + Headers
    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }